### ISSUE TITLE
Make sure all cities show up if all filters are checked

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/reform-map#374] opened 2024-05-30 18:54 UTC
For example, this is with all the filters checked.
![image](https://github.com/ParkingReformNetwork/reform-map/assets/86996158/a84d4071-8d54-4b20-9b9c-f54743173026)

To-do:
- [ ] Figure out why the last few cities aren't showing
- [ ] Create a test to check

**Comment by Eric-Arellano** [comment] 2024-08-04 15:57
Duplicate of https://github.com/ParkingReformNetwork/reform-map/issues/260

**Closed by Eric-Arellano** 2024-08-04 15:57 UTC
